apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: kaniko-azure
spec:
  containers:
    - name: azure-cli
      image: mcr.microsoft.com/azure-cli
      command:
        - cat
      tty: true
      volumeMounts:
        - name: shared-volume
          mountPath: /shared

    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /busybox/sh
      tty: true
      args:
        - "-c"
        - "while true; do sleep 30; done;"
      volumeMounts:
        - name: shared-volume
          mountPath: /shared
  volumes:
    - name: shared-volume
      emptyDir: {}
